### ISSUE TITLE
Check faulty (for Anna)

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-working-data#11]
https://emt.acdh-dev.oeaw.ac.at/faulty.csv

**Comment by SpitzbartAnna** [comment]
@csae8092 @ttechnicus I checked faulty.csv and I just can't get 45_7_0372 right. It is the one where I added two lines on p.4 a few months ago and somehow I can't get it to be valid. 

See also [https://teams.microsoft.com/l/message/19:earu0vKcat422Yhlao52sdWcdho6XR_jMYfKk1K_ndQ1@thread.tacv2/1687858628429?tenantId=ef12f07e-2409-490f-8edc-3bc91a927a71&groupId=b9b3f74f-02df-4d9b-b016-097433b4fdfd&parentMessageId=1687794018631&teamName=ACDH-CH_p_EMT_FamiliensacheHandlungsspielraeumeEleonoraMagdalena&channelName=Allgemein&createdTime=1687858628429&allowXTenantAccess=false
](url)

**Comment by csae8092** [comment]
> @csae8092 @ttechnicus I checked faulty.csv and I just can't get 45_7_0372 right. It is the one where I added two lines on p.4 a few months ago and somehow I can't get it to be valid.
> 
> See also [https://teams.microsoft.com/l/message/19:earu0vKcat422Yhlao52sdWcdho6XR_jMYfKk1K_ndQ1@thread.tacv2/1687858628429?tenantId=ef12f07e-2409-490f-8edc-3bc91a927a71&groupId=b9b3f74f-02df-4d9b-b016-097433b4fdfd&parentMessageId=1687794018631&teamName=ACDH-CH_p_EMT_FamiliensacheHandlungsspielraeumeEleonoraMagdalena&channelName=Allgemein&createdTime=1687858628429&allowXTenantAccess=false ](url)

@ttechnicus can you please have a look into this file and try to make it well formed

**Comment by ttechnicus** [comment]
Yes, I am rebooting to linux at this moment to handle it

**Comment by SpitzbartAnna** [comment]
Thanks so much @ttechnicus @csae8092 !
