### ISSUE TITLE
add missing person ids in correspdesc elements

### ISSUE THREAD

**Issue by csae8092** [emt-project/emt-working-data#15]
in order to resolve issues #4  and #12 please make sure all sender/receiver are tagged with their (correct) baserow-ids

- [x] #16
> #emt_id_person__18 , #emt_perosn_id__18, #emt_person_id_18

- [ ] missing ids, see list below

[['data/work-in-progress/44_10/kasten_blau_44_10_0138.xml', ['#', '#']],
 ['data/work-in-progress/44_3f/kasten_blau_44_3f_0059.xml', ['#', '#']],
 ['data/work-in-progress/44_6/kasten_blau_44_6_0109.xml', ['#', '#']],
 ['data/work-in-progress/44_6/kasten_blau_44_6_0350.xml', ['#', '#']],
 ['data/work-in-progress/44_6/kasten_blau_44_6_0473.xml', ['#', '#']],
 ['data/work-in-progress/44_7/kasten_blau_44_7_0250.xml',
  ['#emt_person_id__18', '#']],
 ['data/work-in-progress/44_8/kasten_blau_44_8_134.xml', ['#', '#']],
 ['data/work-in-progress/45_15/kasten_blau_45_15_0103.xml',
  ['#emt_person_id__50', '#emt_person_id__12']],
 ['data/work-in-progress/45_15/kasten_blau_45_15_0104.xml',
  ['#emt_person_id__50', '#']],
 ['data/work-in-progress/45_15/kasten_blau_45_15_0106.xml',
  ['#', '#emt_person_id__50']],
 ['data/work-in-progress/45_15/kasten_blau_45_15_0348.xml', ['#', '#']],
 ['data/work-in-progress/45_7/kasten_blau_45_7_0113.xml', ['#', '#']],
 ['data/work-in-progress/Korrespondenzakten/korrespondenzakten_1147_0021.xml',
  ['#', '#']],
 ['data/work-in-progress/added_2023/kasten_blau_44_2a_t_1_fol_114r.xml',
  ['#emt_person_id__50', '#emt_person_id__35']],
 ['data/work-in-progress/added_2023/kasten_blau_44_2a_t_1_fol_57r.xml',
  ['#emt_person_id__50', '#emt_person_id__35']]]

e.g. data/work-in-progress/45_15/kasten_blau_45_15_0104.xml

currently looks like this
```xml
<correspAction type="received">
  <persName ref="#">Ferdinand August von Lobkowitz, Fürst von Sagan</persName>
  <placeName ref="#"/>
  <date/>
</correspAction>
```

but should look like

```xml
<correspAction type="received">
  <persName ref="#emt_person_id__12">Ferdinand August von Lobkowitz, Fürst von Sagan</persName>
  <placeName ref="#"/>
  <date/>
</correspAction>
```

**Comment by SpitzbartAnna** [comment]
I'm on it :) thank you very much!

**Comment by SpitzbartAnna** [comment]
@csae8092 what do I do in case there is no apparent sender/recipient? e.g. 44_10_0138 doesn't have either of them, just a date that we guessed from context. I think there are a few examples of this, sometimes it's just a note or newspaper.

**Comment by csae8092** [comment]
@SpitzbartAnna can you find an example and add the filename here to this issue

**Comment by SpitzbartAnna** [comment]
resolved as far as possible
