### ISSUE TITLE
Exchange folio numbers for 44-9 and 44-10?

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-working-data#17]
Hi there!
While correcting errors Frau Keller discovered that for two fascicles (44-9 and 44-10) there are two different folio numbers noted on the pages of the letters (one is from the archive and one is original, Ines noted both of them in the excel file). We accidently used the wrong one, but the right one is already in the metadata of the letters too. Can we just exchange them? I think it might be best if I explained it in person again next week. 

e.g.: 44_9_0037 page 1:

"<div type="page"><pb facs="#facs_1" **n="17 r"** xml:id="Kasten_blau_44_9_0037.jpg" _ed="21 r"_ source="https://files.transkribus.eu/Get?id=POUDLWSDSEVLJBUTXSKZLWMB&amp;fileType=view"/><p"

The value of "n" should actually be the value of "ed" and the other way around. The correct folio number would be 21r, but 17r is an alternative folio number that was added by the archive later on. It just affects 44_9 and 44_10.

**Comment by ttechnicus** [comment]
These files have <pb> elements with missing ed attribute:
./data/work-in-progress/44_10/kasten_blau_44_10_0020.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0031.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0034.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0058.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0077.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0094.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0108.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0108.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0108.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0126.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0129.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0135.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0142.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0147.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0155.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0161.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0191.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0194.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0230.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0245.xml
./data/work-in-progress/44_10/kasten_blau_44_10_0257.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0014.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0086.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0098.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0149.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0171.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0171.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0219.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0231.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0246.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0250.xml
./data/work-in-progress/44_9/kasten_blau_44_9_0258.xml

We noticed that those pb's that have no ed attribute, have a different typed value in "n". Please check and let's discuss it tomorrow.

**Comment by SpitzbartAnna** [comment]
Thank you, I will check it out! :)

**Comment by SpitzbartAnna** [comment]
I'll add the ed manually for these, seems that there was a mix-up of the folio numbers with letters which we added pages on later as well. I think I will be able to finish up 44-10 today. Will commit these with the issue number.

**Comment by SpitzbartAnna** [comment]
> I have already swapped "n" and "ed" values in all other files. If you're going through these 31, you could manually swap them, and the issue is resolved

@ttechnicus I already worked through most of them, only 3 left. Would you mind swapping? I think it is way faster automatically now.

**Comment by SpitzbartAnna** [comment]
All done @ttechnicus :)

**Comment by ttechnicus** [comment]
Thanks!
