### ISSUE TITLE
Chronological reading order

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-working-data#4]
If you pick a date in the calendar, open the letter and then proceed to the next file by clicking on the ">"-button, it opens the next file in the folder not the next one chronologically. Can we rearrange the order? 

ex.g. When I open 44_6_0285, the next one in chronological order should be 44_3d_0002, but it proceeds with the following letters from 44_6.

**Comment by csae8092** [comment]
* we can try this by using the dates of the letters but this might get messed up sometimes in cases where you don't know the exact date 
* a (better) solution would be to encode the sequence of letters in the xml/tei (like schnitzler-briefe is doing, see `<correspContext>` in e.g. https://schnitzler-briefe.acdh.oeaw.ac.at/L02643.xml but I guess this too much to ask from you

I will run some tests to see how well the first approach might work, but I can't promise any quick results

**Comment by SpitzbartAnna** [comment]
`Thank you! :) Sequence of letters sounds like a very accurate solution, I'll check with Frau Keller if we have the ressources to do that.

**Comment by SpitzbartAnna** [comment]
I see one problem though: What do we do if we find new letters and want to add them? Would I have to re-write the whole sequence coming after these letters?

**Comment by csae8092** [comment]
> I see one problem though: What do we do if we find new letters and want to add them? Would I have to re-write the whole sequence coming after these letters?

no, you'd only have the to change the previous and next letter

**Comment by SpitzbartAnna** [comment]
Ok, it'll take me some time, but I think it is worth it in the end to have everything in order. Will talk about this with Frau Keller and report back!

**Comment by csae8092** [comment]
see https://github.com/emt-project/emt-working-data/issues/12

**Comment by ttechnicus** [comment]
Closing this issue as #12 took over and widened the scope
