### ISSUE TITLE
Errors concerning images/ cropping images/...

### ISSUE THREAD

**Issue by SpitzbartAnna** [emt-project/emt-working-data#8]
We found a few errors with images that are not cropped correctly or images that are missing. While we go through every file within the next weeks, I will collect them here:

- 44_6_0489 | Bilder wurden mir nicht   angezeigt, kann aber ein Verbindungsproblem gewesen sein.

- emt___77-8811-korrespondenz-kurfursten-2 | Die Beilage (Memorial) befindet   sich zwischen den beiden Briefseiten; müsste ans Ende gestellt und die Bilder   gedreht werden (liegen quer).

- kasten-blau-44-2a images missing?

- 44_8_0199 | 112v | Blatt schlecht zugeschnitten

- 44_8_0277 |   | enthält zwei nicht zugeordnete   Umschläge (Adressen) von EMT an JW. Die sollten entfernt werden, weil sie   sicher nicht zu dem Brief hier gehören - können wie gesagt nicht zugeordnet   werden.

- 44_8_0494 |   | letztes Bild wird im Querformat   angezeigt

**Comment by csae8092** [comment]
> 44_6_0489 | Bilder wurden mir nicht angezeigt, kann aber ein Verbindungsproblem gewesen sein.

works for me

> kasten-blau-44-2a images missing?

`@type="page"` missing in `div`

> emt___77-8811-korrespondenz-kurfursten-2 | Die Beilage (Memorial) befindet sich zwischen den beiden Briefseiten; müsste ans Ende gestellt und die Bilder gedreht werden (liegen quer).

rearrange the `div type="page"` elements

> 44_8_0277 | enthält zwei nicht zugeordnete Umschläge (Adressen) von EMT an JW. Die sollten entfernt werden, weil sie sicher nicht zu dem Brief hier gehören - können wie gesagt nicht zugeordnet werden.

 remove the matching divs (and facsimiles elements)


rotation -> should be fixed in transkribus

**Comment by csae8092** [comment]
@ttechnicus 
please take care of rearranging/removing the `divs` and adding the missing `@type="page"` attributes
* Ideally you and @SpitzbartAnna can sit together on this so Anna learns what to do;
* please check in a local instance of emt-static, if the modifications in the data fixes the issues mentioned above

**Comment by SpitzbartAnna** [comment]
> @ttechnicus please take care of rearranging/removing the `divs` and adding the missing `@type="page"` attributes
> 




> > 44_6_0489 | Bilder wurden mir nicht angezeigt, kann aber ein Verbindungsproblem gewesen sein.
> 
> works for me
> 
> > kasten-blau-44-2a images missing?
> 
> `@type="page"` missing in `div` --> @ttechnicus took care of that
> 
> > emt___77-8811-korrespondenz-kurfursten-2 | Die Beilage (Memorial) befindet sich zwischen den beiden Briefseiten; müsste ans Ende gestellt und die Bilder gedreht werden (liegen quer).
> 
> rearrange the `div type="page"` elements --> (Note for Anna: Switch the contents from one div to another - rearrange xml-IDs?) 
> 
> > 44_8_0277 | enthält zwei nicht zugeordnete Umschläge (Adressen) von EMT an JW. Die sollten entfernt werden, weil sie sicher nicht zu dem Brief hier gehören - können wie gesagt nicht zugeordnet werden.
> 
> remove the matching divs (and facsimiles elements)
> 
> rotation -> should be fixed in transkribus

**Comment by ttechnicus** [comment]
Add idno to the html (xsl) so that it displays:
Bayerisches Hauptstaatsarchiv (München, Deutschland), Kasten blau 44/2a
<repository> (<settlement>, <country>): <idno>
